=== WashDems-Public/Data/events.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Events",
  "description": "This document describes the fields in the events.json file.",
  "type": "array",
  "items": {
    "type": "object",
    "required": [
      "eventDate",
      "eventStartTime",
      "eventOrgShort",
      "eventOrgType",
      "eventTitle",
      "eventLocationName",
      "eventWeb"
    ],
    "properties": {
      "eventDate": {
        "description": "The day and date on which the event takes place.  (ex: \"Thu, 12/1\")",
        "type": "string",
        "pattern": "^(Mon|Tue|Wed|Thu|Fri|Sat|Sun), \\d\\d?\\/\\d\\d?(\\/(\\d\\d)?\\d\\d)?$"
      },
      "eventStartTime": {
        "description": "The time at which the event starts.  (ex: \"7:00 PM\")",
        "type": "string",
        "pattern": "^\\d\\d?:\\d\\d (AM|PM)$"
      },
      "eventEndTime": {
        "description": "The time at which the event ends.",
        "type": "string",
        "pattern": "^\\d\\d?:\\d\\d (AM|PM)$"
      },
      "eventOrgShort": {
        "description": "Short name for the organization hosting.",
        "type": "string"
      },
      "eventOrgType": {
        "description": "A descriptor of the organization type.  (ex: \"LD\", \"County\", \"State\", \"Ally\")",
        "enum": [
          "State",
          "County",
          "LD",
          "State Young",
          "County Young",
          "College Young",
          "HS Young",
          "Caucus",
          "CD",
          "Ally"
        ]
      },
      "eventTitle": {
        "description": "A title for the event. Please do NOT include the name of the organization hosting the event.",
        "type": "string"
      },
      "eventLocationName": {
        "description": "Name of the location where the event will be held. (ex: \"Yakima County Democrats office\", \"Mercer Island Community Center\", \"Home of John Smith\")",
        "type": "string"
      },
      "eventLocationStreet": {
        "description": "Street address for the event location. (ex: \"123 Main St.\")",
        "type": "string"
      },
      "eventLocationCity": {
        "description": "City for the event location (ex: \"Wenatchee\")",
        "type": "string"
      },
      "eventLocationST": {
        "description": "Two-letter state abberviation for the event location (ex: \"WA\")",
        "type": "string",
        "maxLength": 2
      },
      "eventLocationZip": {
        "description": "ZIP code for the event location (ex: \"98040\")",
        "type": "string",
        "pattern": "^(|\\d{5}|\\d{5}-\\d{4})$"
      },
      "eventWeb": {
        "description": "Web address where visitors can find more information about this event.",
        "type": "string",
        "format": "uri"
      },
      "eventFbId": {
        "description": "Facebook ID for this event (ex: \"1811175945791682\")",
        "type": "string",
        "pattern": "^\\d+$"
      },
      "eventDescription": {
        "description": "Additional details about this event. (ex: \"Doors open at 6pm and program starts at 7pm\", \"Dinner will be served\", \"Suggested $20 donation\")",
        "type": "string"
      }
    }
  }
}

=== WashDems-Public/Data/events/2017-04.json
[
  {
    "eventDate": "Fri, 4/7",
    "eventStartTime": "4:00 PM",
    "eventOrgShort": "Washington",
    "eventOrgType": "State Young",
    "eventTitle": "Convention 2017",
    "eventLocationName": "Red Lion Hotel Olympia",
    "eventLocationStreet": "2300 Evergreen Park Dr. SW",
    "eventLocationCity": "Olympia",
    "eventLocationST": "WA",
    "eventLocationZip": "98502",
    "eventWeb": "http://ydwa.org/events/ydwa-convention-2017-in-olympia/",
    "eventFbId": "1498456823528419",
    "eventDescription": "Awards Banquet Keynote Speaker is WA Attorney General Bob Ferguson"
  },
  {
    "eventDate": "Sat, 4/22",
    "eventStartTime": "1:00 PM",
    "eventEndTime": "5:00 PM",
    "eventOrgShort": "Washington",
    "eventOrgType": "State",
    "eventTitle": "WSDCC Meetings",
    "eventLocationName": "Walla Walla",
    "eventLocationStreet": "",
    "eventLocationCity": "Walla Walla",
    "eventLocationST": "WA",
    "eventLocationZip": "",
    "eventWeb": "",
    "eventDescription": "Washington State Democratic Central Committee (WSDCC) spring meetings in Walla Walla"
  },
  {
    "eventDate": "Sat, 4/29",
    "eventStartTime": "6:00 PM",
    "eventOrgShort": "NPI",
    "eventOrgType": "Ally",
    "eventTitle": "2017 Spring Fundraising Gala",
    "eventLocationName": "Mercer Island Community & Event Center",
    "eventLocationStreet": "8236 SE 24th St.",
    "eventLocationCity": "Mercer Island",
    "eventLocationST": "WA",
    "eventLocationZip": "98040",
    "eventWeb": "https://www.nwprogressive.org/gala/",
    "eventDescription": "Reception starts at 6 PM, main program at 7 PM.  Full dinner buffet with vegetarian choices; beer and wine available from cash bar"
  }
]

=== WashDems-Public/Data/events/2017-03.json
[
  {
    "eventDate": "Sat, 3/18",
    "eventStartTime": "10:00 AM",
    "eventEndTime": "12:00 PM",
    "eventOrgShort": "27th",
    "eventOrgType": "LD",
    "eventTitle": "Coffee with Chair Lynda Foster",
    "eventLocationName": "B Sharp Coffee House",
    "eventLocationStreet": "706 Opera Alley",
    "eventLocationCity": "Tacoma",
    "eventLocationST": "WA",
    "eventLocationZip": "98402",
    "eventWeb": "https://www.facebook.com/events/393822487652566/",
    "eventFbId": "393822487652566",
    "eventDescription": "These are intended to space for anyone to show up and talk about anything on their mind"
  },
  {
    "eventDate": "Sat, 3/18",
    "eventStartTime": "2:00 PM",
    "eventEndTime": "4:00 PM",
    "eventOrgShort": "3rd",
    "eventOrgType": "CD",
    "eventTitle": "Local Party Politics 101",
    "eventLocationName": "Camas Public Library",
    "eventLocationStreet": "625 NE 4th Ave.",
    "eventLocationCity": "Camas",
    "eventLocationST": "WA",
    "eventLocationZip": "98607",
    "eventWeb": "https://www.facebook.com/events/706707589499205/",
    "eventFbId": "706707589499205",
    "eventDescription": "Learn how to get involved and organized politically with WA Dems Exec. Board member Justin Oberg"
  },
  {
    "eventDate": "Sat, 3/18",
    "eventStartTime": "4:00 PM",
    "eventEndTime": "9:00 PM",
    "eventOrgShort": "Pacific",
    "eventOrgType": "County",
    "eventTitle": "92nd Annual Crab Feed",
    "eventLocationName": "Willapa Harbor Community Building",
    "eventLocationStreet": "916 W. First Street",
    "eventLocationCity": "South Bend",
    "eventLocationST": "WA",
    "eventLocationZip": "98586",
    "eventWeb": "http://www.pacificcountydemocrats.com/annual-crab-feed.html",
    "eventFbId": "1846722112282287",
    "eventDescription": "4pm: Social Hour, 5pm: Dinner and Program.  Includes: Live Auction, Silent Auction, Raffle, Speakers, and Pacific County Democrat of the Year"
  }
]

=== WashDems-Public/Data/events.json
[
  {
    "eventDate": "Sat, 3/18",
    "eventStartTime": "10:00 AM",
    "eventEndTime": "12:00 PM",
    "eventOrgShort": "27th",
    "eventOrgType": "LD",
    "eventTitle": "Coffee with Chair Lynda Foster",
    "eventLocationName": "B Sharp Coffee House",
    "eventLocationStreet": "706 Opera Alley",
    "eventLocationCity": "Tacoma",
    "eventLocationST": "WA",
    "eventLocationZip": "98402",
    "eventWeb": "https://www.facebook.com/events/393822487652566/",
    "eventFbId": "393822487652566",
    "eventDescription": "These are intended to space for anyone to show up and talk about anything on their mind"
  },
  {
    "eventDate": "Sat, 4/22",
    "eventStartTime": "1:00 PM",
    "eventEndTime": "5:00 PM",
    "eventOrgShort": "WA",
    "eventOrgType": "State",
    "eventTitle": "WSDCC Meetings",
    "eventLocationName": "Walla Walla",
    "eventLocationStreet": "",
    "eventLocationCity": "Walla Walla",
    "eventLocationST": "WA",
    "eventLocationZip": "",
    "eventWeb": "",
    "eventDescription": "Washington State Democratic Central Committee (WSDCC) spring meetings in Walla Walla"
  },
  {
    "eventDate": "Sat, 4/29",
    "eventStartTime": "6:00 PM",
    "eventOrgShort": "NPI",
    "eventOrgType": "Ally",
    "eventTitle": "2017 Spring Fundraising Gala",
    "eventLocationName": "Mercer Island Community & Event Center",
    "eventLocationStreet": "8236 SE 24th St.",
    "eventLocationCity": "Mercer Island",
    "eventLocationST": "WA",
    "eventLocationZip": "98040",
    "eventWeb": "https://www.nwprogressive.org/gala/",
    "eventDescription": "Reception starts at 6 PM, main program at 7 PM.  Full dinner buffet with vegetarian choices; beer and wine available from cash bar"
  }  
]
